# Generated by Django 5.2.12 on 2026-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagelog',
            name='error_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='feedback_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='file_size_kb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='is_regenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiusagelog',
            name='processing_time',
            field=models.FloatField(default=0),
        ),
    ]
