# Generated by Django 5.2.12 on 2026-04-27 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_aiusagelog_error_type_aiusagelog_feedback_stars_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên khoản chi')),
                ('category', models.CharField(choices=[('SERVER', 'Chi phí Server / Hosting'), ('AI_API', 'Chi phí AI API (GPT-4o, OpenAI...)'), ('DOMAIN', 'Tên miền / SSL'), ('MARKETING', 'Marketing / Quảng cáo'), ('TOOLS', 'Công cụ / Phần mềm'), ('SALARY', 'Lương / Nhân sự'), ('TAX', 'Thuế / Phí pháp lý'), ('OTHER', 'Chi phí khác')], default='OTHER', max_length=20, verbose_name='Danh mục')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Số tiền (VNĐ)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('expense_date', models.DateField(verbose_name='Ngày chi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khoản chi',
                'verbose_name_plural': 'Các khoản chi',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
