# Generated by Django 5.2.12 on 2026-05-08 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_add_platform_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_finance', models.BooleanField(default=False, verbose_name='Xem tài chính')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='Quản lý người dùng')),
                ('can_view_ai_logs', models.BooleanField(default=False, verbose_name='Xem AI Logs')),
                ('can_view_vouchers', models.BooleanField(default=False, verbose_name='Quản lý Voucher')),
                ('can_view_notifications', models.BooleanField(default=False, verbose_name='Quản lý Thông báo')),
                ('can_view_system', models.BooleanField(default=False, verbose_name='Quản lý Hệ thống')),
                ('can_view_blog', models.BooleanField(default=True, verbose_name='Quản lý Blog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phân quyền Admin',
                'verbose_name_plural': 'Phân quyền Admin',
            },
        ),
    ]
