# Generated by Django 5.2.14 on 2026-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_adminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpermission',
            name='role_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vị trí/Chức vụ'),
        ),
    ]
