# Generated by Django 5.2.12 on 2026-05-22 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_adminpermission_role_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('is_malicious', models.BooleanField(default=False, verbose_name='Phát hiện độc hại')),
                ('analysis_reason', models.TextField(blank=True, null=True, verbose_name='Lý do (AI phân tích)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký Bảo mật AI',
                'verbose_name_plural': 'Nhật ký Bảo mật AI',
                'ordering': ['-timestamp'],
            },
        ),
    ]
