# Generated by Django 5.2.14 on 2026-05-22 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_securitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='Phiên Chat')),
                ('collected_info', models.JSONField(blank=True, default=dict, verbose_name='Thông tin thu thập')),
                ('chat_history', models.JSONField(blank=True, default=list, verbose_name='Lịch sử Chat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Khách hàng tiềm năng',
                'verbose_name_plural': 'Khách hàng tiềm năng',
                'ordering': ['-updated_at'],
            },
        ),
    ]
