import os
import json

directory = 'c:/Mia Analyst/templates'

translations = {
    '! Tôi là AI phân tích dữ liệu Mia. Hãy chọn nguồn dữ liệu bên phải và đặt câu hỏi cho tôi để bắt đầu chuyển đổi dữ liệu thành hành động.': '! I am Mia, your AI data analyst. Select a data source on the right and ask me questions to start turning your data into action.',
    'Báo cáo mới': 'New Report',
    ', chúng tôi coi trọng sự riêng tư của bạn hơn bất cứ điều gì. Dữ liệu kinh doanh của bạn là tài sản quý giá nhất, và mục tiêu của chúng tôi là bảo vệ nó bằng những công nghệ bảo mật tiên tiến nhất hiện nay.': ', we value your privacy above all else. Your business data is your most precious asset, and our goal is to protect it using the most advanced security technologies.',
    '. Tuy nhiên, các báo cáo và kết quả phân tích được tạo ra từ dữ liệu của bạn sẽ thuộc quyền sở hữu của bạn.': '. However, the reports and analytical results generated from your data remain entirely yours.',
    '1. Chấp nhận điều khoản': '1. Acceptance of Terms',
    '1. Cài đặt Telegram Bot': '1. Setup Telegram Bot',
    '1. Thu thập thông tin': '1. Information Collection',
    '123456789:AAH... (Từ BotFather)': '123456789:AAH... (From BotFather)',
    '2. Sử dụng dữ liệu': '2. Data Usage',
    '2. Tài khoản người dùng': '2. User Accounts',
    '2. Tạo lịch gửi báo cáo (Task mới)': '2. Create Report Task (New Task)',
    '2027 & Xa hơn': '2027 & Beyond',
    '3. Bảo mật và Lưu trữ': '3. Security and Storage',
    '3. Quyền sở hữu trí tuệ': '3. Intellectual Property Rights',
    '4. Giới hạn trách nhiệm': '4. Limitation of Liability',
    '4. Liên hệ': '4. Contact',
    '5. Chấm dứt dịch vụ': '5. Termination of Service',
    '6. Thay đổi điều khoản': '6. Changes to Terms',
    'Báo cáo cuối ngày': 'End of Day Report',
    'Báo cáo của tôi': 'My Reports',
    'Bạn cam kết cung cấp thông tin chính xác và cập nhật khi đăng ký.': 'You agree to provide accurate and up-to-date information upon registration.',
    'Bạn chịu trách nhiệm bảo mật thông tin đăng nhập của mình.': 'You are responsible for keeping your login credentials secure.',
    'Bạn có gợi ý tính năng nào cho chúng tôi?': 'Do you have any feature suggestions for us?',
    'Bạn có quyền xóa vĩnh viễn các file và lịch sử chat bất cứ lúc nào.': 'You have the right to permanently delete files and chat history at any time.',
    'Cam kết của chúng tôi': 'Our Commitment',
    'Chào mừng bạn đến với Mia AI Data Analytics. Bằng việc truy cập hoặc sử dụng dịch vụ của chúng tôi, bạn đồng ý tuân thủ các điều khoản và điều kiện được nêu dưới đây.': 'Welcome to Mia AI Data Analytics. By accessing or using our services, you agree to comply with the terms and conditions outlined below.',
    'Chính sách Bảo mật': 'Privacy Policy',
    'Chúng tôi chỉ thu thập những thông tin cần thiết để cung cấp dịch vụ tốt nhất cho bạn:': 'We only collect necessary information to provide you with the best service:',
    'Chúng tôi có quyền tạm ngừng hoặc chấm dứt quyền truy cập nếu bạn vi phạm nghiêm trọng các điều khoản này hoặc sử dụng hệ thống vào các mục đích bất hợp pháp.': 'We reserve the right to suspend or terminate access if you severely violate these terms or use the system for illegal purposes.',
    'Chúng tôi có thể cập nhật các Điều khoản này theo thời gian. Việc tiếp tục sử dụng dịch vụ sau khi có thay đổi đồng nghĩa với việc bạn chấp thuận các điều khoản mới.': 'We may update these Terms over time. Continued use of the service after changes implies your acceptance of the new terms.',
    'Chúng tôi không ngừng tiến hóa để mang lại trải nghiệm phân tích dữ liệu đột phá nhất. Dưới đây là những gì đang diễn ra tại Mia.': 'We are constantly evolving to provide the most breakthrough data analysis experience. Here is what is happening at Mia.',
    'Chúng tôi áp dụng các tiêu chuẩn bảo mật chuẩn doanh nghiệp:': 'We apply enterprise-grade security standards:',
    'Chưa có DB.': 'No DB connected.',
    'Chưa có lịch sử.': 'No history available.',
    'Chưa có task.': 'No tasks available.',
    'Chỉ bạn mới có quyền truy cập vào dữ liệu và kết quả phân tích của mình.': 'Only you have access to your data and analytical results.',
    'Chỉ số': 'Metric',
    'Chọn Sheet Phân Tích': 'Select Analysis Sheet',
    'Chọn bộ não AI': 'Select AI Brain',
    'Chọn ngày': 'Select date',
    'Cuối tháng': 'End of Month',
    'Cải thiện độ chính xác của phản hồi AI đối với riêng tài khoản của bạn.': 'Improve the accuracy of AI responses for your account specifically.',
    'Cấu trúc Dữ liệu': 'Data Structure',
    'Cập nhật lần cuối: 27 tháng 4, 2026': 'Last updated: April 27, 2026',
    'Cột': 'Column',
    'Dòng': 'Row',
    'Dữ liệu của bạn hiện tại rất đẹp và sẵn sàng để phân tích.': 'Your data currently looks great and is ready for analysis.',
    'Dữ liệu của bạn được sử dụng duy nhất cho các mục đích:': 'Your data is solely used for the following purposes:',
    'Dữ liệu tải lên: Các tệp Excel, CSV bạn chủ động tải lên để phân tích.': 'Uploaded data: Excel, CSV files you actively upload for analysis.',
    'Dữ liệu được truyền tải qua giao thức HTTPS và mã hóa lúc nghỉ bằng chuẩn AES-256.': 'Data is transmitted via HTTPS and encrypted at rest using AES-256 standard.',
    'Gemini 1.5 Pro chỉ dành cho thành viên Plus và Premium. Hãy nâng cấp để sử dụng bộ não AI thông minh nhất thế giới!': 'Gemini 1.5 Pro is exclusively for Plus and Premium members. Upgrade now to use the smartest AI brain in the world!',
    'Giá trị': 'Value',
    'Giờ gửi báo cáo': 'Report Delivery Time',
    'Gói hiện tại': 'Current Plan',
    'Gửi thông báo về tài khoản và các cập nhật quan trọng của hệ thống.': 'Send notifications about your account and important system updates.',
    'Gửi ý tưởng của bạn': 'Submit your ideas',
    'Hoàn thành': 'Completed',
    'Hướng dẫn': 'Documentation',
    'Hệ sinh thái AI tích hợp hoàn toàn vào ERP doanh nghiệp toàn cầu. Mia trở thành bộ não của mọi quyết định kinh doanh dữ liệu.': 'AI ecosystem fully integrated into global enterprise ERPs. Mia becomes the brain of every data-driven business decision.',
    'Hệ thống dự báo AI (Predictive Forecasting) – dự đoán doanh thu và tồn kho cho 3-6 tháng tới dựa trên dữ liệu lịch sử. Hỗ trợ kết nối BigQuery & Amazon Redshift.': 'AI Predictive Forecasting system – forecasting revenue and inventory for the next 3-6 months based on historical data. Supports connecting BigQuery & Amazon Redshift.',
    'Hỏi Mia bất cứ điều gì...': 'Ask Mia anything...',
    'Khám phá cách Mia giúp bạn làm việc nhanh hơn.': 'Discover how Mia helps you work faster.',
    'Kéo thả nhanh': 'Drag & Drop',
    'Lưu': 'Save',
    'Lưu Task Mới': 'Save New Task',
    'Lưu vào Dashboard': 'Save to Dashboard',
    'Lưu ý quan trọng: Chúng tôi tuyệt đối không sử dụng dữ liệu kinh doanh của khách hàng để huấn luyện các mô hình AI công khai.': 'Important note: We strictly never use our customers business data to train public AI models.',
    'Lịch sử': 'History',
    'Lịch sử gần đây': 'Recent History',
    'Lỗi kết nối': 'Connection Error',
    'Lộ trình Phát triển': 'Development Roadmap',
    'MIA Tự động Phân tích': 'MIA Automated Analysis',
    'MIA tự động đề xuất insight và xu hướng ẩn trong dự liệu mà không cần bạn đặt câu hỏi.': 'MIA automatically suggests insights and hidden trends in data without you asking questions.',
    'Mia Assistant có thể mắc sai sót. Hãy kiểm tra những thông tin quan trọng.': 'Mia Assistant may make mistakes. Please double-check important information.',
    'Mã hóa đầu cuối:': 'End-to-End Encryption:',
    'Mặc dù chúng tôi nỗ lực cung cấp phân tích chính xác nhất có thể, Mia AI Data Analytics là một công cụ hỗ trợ ra quyết định. Chúng tôi không chịu trách nhiệm cho bất kỳ tổn thất kinh doanh nào phát sinh từ các quyết định dựa trên kết quả phân tích của AI.': 'Although we strive to provide the most accurate analysis possible, Mia AI Data Analytics is a decision-support tool. We are not liable for any business losses arising from decisions based on AI analysis results.',
    'Mặc định hệ thống': 'System Default',
    'Mọi hoạt động diễn ra dưới tài khoản của bạn sẽ được xem là trách nhiệm của bạn.': 'Any activities occurring under your account are considered your responsibility.',
    'Mới': 'New',
    'Nguồn Dữ liệu': 'Data Source',
    'Nguồn đang chọn': 'Selected Source',
    'Nâng cấp lõi AI sang Gemini 1.5 Pro và 2.5 Flash, triển khai tính năng Automation với Telegram và hệ thống bảo mật doanh nghiệp.': 'Upgrade AI core to Gemini 1.5 Pro and 2.5 Flash, deploy Automation feature with Telegram, and enterprise security system.',
    'Nâng cấp phí ngay': 'Upgrade Now',
    'Nạp': 'Load',
    'Nếu bạn có bất kỳ câu hỏi nào về chính sách này, vui lòng liên hệ với chúng tôi qua email:': 'If you have any questions regarding this policy, please contact us via email:',
    'Phân quyền truy cập:': 'Access Authorization:',
    'Phản hồi tức thì, phù hợp với câu hỏi đơn giản và tra cứu dữ liệu nhanh.': 'Instant feedback, suitable for simple questions and quick data lookups.',
    'Quay lại': 'Go Back',
    'Quay lại trang chủ': 'Back to Homepage',
    'Sai định dạng': 'Invalid Format',
    'Sắp tới': 'Upcoming',
    'Thông minh': 'Intelligent',
    'Thông tin thanh toán: Được xử lý bởi các đối tác thanh toán bảo mật, chúng tôi không lưu giữ thông tin thẻ tín dụng của bạn.': 'Billing information: Processed and secured by partnered payment gateways, we do not store your credit card information.',
    'Thông tin tài khoản: Tên, email, và mật khẩu đã mã hóa.': 'Account information: Name, email, and encrypted password.',
    'Thất bại': 'Failed',
    'Thống kê nhanh': 'Quick Stats',
    'Thử lại ngay': 'Try again now',
    'Thực hiện các yêu cầu phân tích và báo cáo của bạn.': 'Fulfill your analytical reporting requests.',
    'Tiếp theo': 'Next',
    'Toàn bộ nội dung, mã nguồn, thuật toán AI và giao diện trên hệ thống thuộc sở hữu độc quyền của': 'All content, source code, AI algorithms, and UI on the platform are exclusively owned by',
    'Trải nghiệm AI Mạnh mẽ nhất': 'Most Powerful AI Experience',
    'Tích hợp API trực tiếp với Shopee Seller, TikTok Shop & Lazada để tự động kéo dữ liệu đơn hàng. Ra mắt tính năng "Smart Data Cleaning" – tự động sửa lỗi chính tả và định dạng dữ liệu thô.': 'Direct API Integration with Shopee Seller, TikTok Shop & Lazada for automatic order sync. Launching "Smart Data Cleaning" – automatic fixing of typography errors in raw data.',
    'Tóm tắt doanh thu, báo cáo LTV và đưa ra 3 lời khuyên...': 'Summarize revenue, LTV report and suggest 3 tips...',
    'Tại': 'At',
    'Tạo lại': 'Regenerate',
    'Tải Excel / CSV': 'Upload Excel / CSV',
    'Tầm nhìn': 'Vision',
    'Việc sử dụng dịch vụ đồng nghĩa với việc bạn đã đọc, hiểu và chấp thuận các Điều khoản này. Nếu bạn đại diện cho một doanh nghiệp, bạn cam kết có đủ thẩm quyền để ràng buộc doanh nghiệp đó với các điều khoản này.': 'Using the service indicates you have read, understood, and accepted these Terms. If you represent a business, you commit to having sufficient authority to bind that business.',
    'Vui lòng chọn file .xlsx, .xls hoặc .csv.': 'Please select a .xlsx, .xls, or .csv file.',
    'Xin chào': 'Hello',
    'Xóa dữ liệu:': 'Data Deletion:',
    'Xử lý logic cực phức tạp, phân tích dữ liệu sâu và lập luận đa bước (Best for Analytics).': 'Capable of complex logic processing, deep data analytics, and multi-step reasoning (Best for Analytics).',
    'Yêu cầu gói PLUS/PREMIUM': 'Requires PLUS/PREMIUM plan',
    'Đang thực hiện': 'In progress',
    'Đang xử lý...': 'Processing...',
    'Đang được kiến tạo': 'Under Construction',
    'Điều khoản Dịch vụ': 'Terms of Service',
    'Đánh giá:': 'Review:',
    'Đã làm sạch dữ liệu thành công!': 'Data cleaned successfully!',
    'Đóng Panel': 'Close Panel',
    'Đầu tháng': 'Start of Month',
    'Đề xuất nhanh': 'Quick Recommendation',
    'Để sau': 'Later',
    'Đồng bộ đơn hàng tự động': 'Auto Order Sync',
    '• K tối ưu (Elbow):': '• Optimal K (Elbow):',
    '✏️ Đang chỉnh sửa Task': '✏️ Editing Task'
}

count = 0
for root, _, files in os.walk(directory):
    for file in files:
        if file.endswith('_en.html'):
            path = os.path.join(root, file)
            with open(path, 'r', encoding='utf-8') as f:
                content = f.read()
            original_content = content
            
            for vi, en in translations.items():
                content = content.replace(vi, en)
                
            if content != original_content:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(content)
                count += 1

print(f'Done replacing in {count} files.')
