import os
import re

file_path = "templates/landing_en.html"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

translations = {
    r'\{\{ "Mia AI Data Analytics - Nền tảng Phân tích Dữ liệu AI Tối ưu cho Doanh nghiệp" \}\}': 'Mia AI Data Analytics - The Ultimate AI Data Analytics Platform for Enterprises',
    r'\{\{ "Về chúng tôi" \}\}': 'About Us',
    r'\{\{ "Dịch vụ" \}\}': 'Services',
    r'\{\{ "Quy trình" \}\}': 'Workflow',
    r'\{\{ "Bảng giá" \}\}': 'Pricing',
    r'\{\{ "Hỏi đáp" \}\}': 'FAQ',
    r'\{\{ "Blog" \}\}': 'Blog',
    r'\{\{ "Đăng nhập" \}\}': 'Login',
    r'\{\{ "Bắt đầu" \}\}': 'Get Started',
    r'\{\{ "Bắt đầu miễn phí" \}\}': 'Start for Free',
    r'\{\{ "Phiên bản 2.0 đã sẵn sàng" \}\}': 'Version 2.0 is Live',
    r'\{\{ "Biến dữ liệu" \}\}': 'Turn Data',
    r'\{\{ "thành" \}\}': 'into',
    r'\{\{ "Quyền năng." \}\}': 'Power.',
    r'\{\{ "Nền tảng AI thế hệ mới giúp bạn kết nối, phân tích và tối ưu hóa dữ liệu Excel, CSV & SQL chỉ bằng ngôn ngữ tự nhiên. Không cần Code, không cần kiến thức kỹ thuật sâu." \}\}': 'The next-generation AI platform that helps you connect, analyze, and optimize Excel, CSV & SQL data using just natural language. No coding required, no deep technical expertise needed.',
    r'\{\{ "Khám phá ngay" \}\}': 'Explore Now',
    r'\{\{ "Đăng ký ngay" \}\}': 'Sign Up Now',
    r'\{\{ "Câu chuyện về Mia" \}\}': 'The Mia Story',
    r'\{\{ "Sứ mệnh dân chủ hóa" \}\}': 'The Mission of Democratizing',
    r'\{\{ "Dữ liệu thông minh." \}\}': 'Smart Data.',
    r'\{\{ "Mia AI Data Analytics không chỉ là một công cụ phân tích. Chúng tôi ra đời từ niềm tin rằng: Dữ liệu là tài sản quý giá nhất của mọi doanh nghiệp, nhưng quyền năng truy cập nó không nên chỉ thuộc về những người biết lập trình." \}\}': 'Mia AI Data Analytics is not just an analysis tool. We were born from the belief that: Data is the most valuable asset of any enterprise, but the power to access it should not belong exclusively to those who know how to code.',
    r'\{\{ "Được thành lập bởi đội ngũ chuyên gia về AI và dữ liệu tại Việt Nam, Mia hướng tới việc phá bỏ rào cản kỹ thuật. Chúng tôi kết hợp sức mạnh của mô hình ngôn ngữ lớn \(Gemini AI\) với hạ tầng xử lý dữ liệu hiện đại để tạo ra một \'Trợ lý ảo\' thực thụ cho phòng kinh doanh, kế toán và quản lý." \}\}': 'Founded by a team of AI and data experts in Vietnam, Mia aims to break down technical barriers. We combine the power of Large Language Models (Gemini AI) with modern data processing infrastructure to create a true \'Virtual Assistant\' for sales, accounting, and management departments.',
    r'\{\{ "Tầm nhìn" \}\}': 'Vision',
    r'\{\{ "Trở thành nền tảng phân tích dữ liệu AI số 1 Đông Nam Á vào năm 2030." \}\}': 'To become the #1 AI data analytics platform in Southeast Asia by 2030.',
    r'\{\{ "Giá trị" \}\}': 'Core Values',
    r'\{\{ "Sự đơn giản, Chính xác và Bảo mật tuyệt đối cho mọi khách hàng." \}\}': 'Simplicity, Accuracy, and Absolute Security for every customer.',
    r'\{\{ "Công nghệ AI" \}\}': 'AI Technology',
    r'\{\{ "Vận hành bởi Gemini 1.5 Pro & 2.5 Flash cùng Machine Learning chuyên sâu." \}\}': 'Powered by Gemini 1.5 Pro & 2.5 Flash along with deep Machine Learning.',
    r'\{\{ "Sáng tạo" \}\}': 'Innovation',
    r'\{\{ "Luôn tiên phong trong việc tích hợp các mô hình AI mới nhất vào thực tiễn." \}\}': 'Always pioneering in integrating the latest AI models into practice.',
    r'\{\{ "Dịch vụ chi tiết" \}\}': 'Detailed Services',
    r'\{\{ "Giải pháp toàn diện cho" \}\}': 'Comprehensive Solutions for',
    r'\{\{ "Kỷ nguyên số." \}\}': 'The Digital Era.',
    r'\{\{ "Mia được thiết kế để giải quyết mọi nỗi đau của doanh nghiệp trong việc quản lý và trích xuất giá trị từ dữ liệu thô." \}\}': 'Mia is designed to solve all enterprise pain points in managing and extracting value from raw data.',
    r'\{\{ "AI Chat Insights" \}\}': 'AI Chat Insights',
    r'\{\{ "Hỏi Mia bất cứ điều gì về dữ liệu của bạn. \'Tại sao doanh thu tháng này giảm?\' - Mia sẽ phân tích và trả lời ngay lập tức." \}\}': 'Ask Mia anything about your data. \'Why did sales drop this month?\' - Mia will analyze and answer instantly.',
    r'\{\{ "Ngôn ngữ tự nhiên" \}\}': 'Natural Language',
    r'\{\{ "Gemini 1.5 Pro" \}\}': 'Gemini 1.5 Pro',
    r'\{\{ "Phân tích thời gian thực" \}\}': 'Real-time Analysis',
    r'\{\{ "Excel Intelligence" \}\}': 'Excel Intelligence',
    r'\{\{ "Tải lên file Excel khổ lớn và Mia sẽ tự động dọn dẹp, cấu trúc lại và gợi ý các biểu đồ phân tích xu hướng quan trọng." \}\}': 'Upload large Excel files and Mia will automatically clean, restructure, and suggest important trend analysis charts (Exploratory Data Analysis).',
    r'\{\{ "Làm sạch thông minh" \}\}': 'Smart Cleaning',
    r'\{\{ "Phát hiện xu hướng" \}\}': 'Trend Detection',
    r'\{\{ "CSV/XLSX" \}\}': 'CSV/XLSX',
    r'\{\{ "Secure Reporting" \}\}': 'Secure Reporting',
    r'\{\{ "Bảo mật dữ liệu chuẩn ngân hàng. Tự động xuất báo cáo PDF/Excel định kỳ gửi qua Email hoặc Telegram của bạn." \}\}': 'Bank-grade data security. Automatically export periodic PDF/Excel reports sent via your Email or Telegram.',
    r'\{\{ "Mã hóa AES-256" \}\}': 'AES-256 Encryption',
    r'\{\{ "Báo cáo tự động" \}\}': 'Automated Reporting',
    r'\{\{ "Đa kênh" \}\}': 'Omnichannel',
    r'\{\{ "Quy trình làm việc" \}\}': 'Workflow',
    r'\{\{ "Chỉ 4 bước để làm chủ dữ liệu." \}\}': 'Just 4 steps to master your data.',
    r'\{\{ "Kết nối" \}\}': 'Connect',
    r'\{\{ "Kết nối dễ dàng các tệp Excel, CSV hoặc cơ sở dữ liệu. Mia sẽ tự động quét, phân loại và chuẩn bị dữ liệu cho phân tích chuyên sâu." \}\}': 'Easily connect Excel, CSV files or databases. Mia will automatically scan, classify, and prepare data for in-depth analysis.',
    r'\{\{ "Hỏi Mia" \}\}': 'Ask Mia',
    r'\{\{ "Đặt bất kỳ câu hỏi nào về kinh doanh bằng ngôn ngữ tự nhiên. Mia hiểu rõ ngữ cảnh và cung cấp câu trả lời chính xác, thông minh." \}\}': 'Ask any business question in natural language. Mia understands the context and provides accurate, smart answers.',
    r'\{\{ "Phân tích" \}\}': 'Analyze',
    r'\{\{ "AI thực hiện hàng nghìn phép toán để tìm xu hướng, phát hiện bất thường và tóm tắt Insight giá trị qua các biểu đồ trực quan." \}\}': 'AI performs thousands of calculations to find trends, detect anomalies, and summarize valuable Insights through visual charts.',
    r'\{\{ "Hành động" \}\}': 'Action',
    r'\{\{ "Nhận các gợi ý chiến lược thực tế từ AI để tối ưu hóa quy trình, tăng trưởng doanh thu và đưa ra quyết định dựa trên số liệu thực." \}\}': 'Receive practical strategic suggestions from AI to optimize processes, grow revenue, and make data-driven decisions.',
    r'\{\{ "Bảng giá linh hoạt" \}\}': 'Flexible Pricing',
    r'\{\{ "Phù hợp cho mọi quy mô doanh nghiệp." \}\}': 'Suitable for all enterprise scales.',
    r'\{\{ "Cơ bản" \}\}': 'Basic',
    r'\{\{ "Miễn phí" \}\}': 'Free',
    r'\{\{ "Dành cho trải nghiệm AI Chat Engine cơ bản." \}\}': 'For experiencing the basic AI Chat Engine.',
    r'\{\{ "20 câu hỏi phân tích / tháng" \}\}': '20 analysis queries / month',
    r'\{\{ "AI Chat Engine cơ bản" \}\}': 'Basic AI Chat Engine',
    r'\{\{ "Phân tích 1 File Excel/CSV" \}\}': 'Analyze 1 Excel/CSV File',
    r'\{\{ "Xuất báo cáo định dạng Text" \}\}': 'Export Text-format Reports',
    r'\{\{ "Bảo mật SSL tiêu chuẩn" \}\}': 'Standard SSL Security',
    r'\{\{ "Sử dụng ngay" \}\}': 'Start Now',
    r'\{\{ "Phổ biến nhất" \}\}': 'Most Popular',
    r'\{\{ "Nâng cao" \}\}': 'Advanced',
    r'\{\{ "/tháng" \}\}': '/month',
    r'\{\{ "Phân tích chuyên sâu cho các shop và startup." \}\}': 'In-depth analysis for shops and startups.',
    r'\{\{ "500 câu hỏi phân tích / tháng" \}\}': '500 analysis queries / month',
    r'\{\{ "Phân tích Python/Pandas chuyên môn" \}\}': 'Professional Python/Pandas Analysis',
    r'\{\{ "Nhận diện xu hướng tự động" \}\}': 'Automated Trend Detection',
    r'\{\{ "Không giới hạn số dòng dữ liệu" \}\}': 'Unlimited data rows',
    r'\{\{ "Thư viện biểu đồ AI đa dạng" \}\}': 'Diverse AI Chart Library',
    r'\{\{ "Lưu lịch sử phân tích 30 ngày" \}\}': 'Save analysis history for 30 days',
    r'\{\{ "Hỗ trợ ưu tiên qua Email 24/7" \}\}': '24/7 Priority Email Support',
    r'\{\{ "Nâng cấp ngay" \}\}': 'Upgrade Now',
    r'\{\{ "Chuyên nghiệp" \}\}': 'Professional',
    r'\{\{ "Trợ lý AI chiến lược cho doanh nghiệp thực thụ." \}\}': 'Strategic AI Assistant for real enterprises.',
    r'\{\{ "Không giới hạn câu hỏi \\(Full Flow\\)" \}\}': 'Unlimited queries (Full Flow)',
    r'\{\{ "Machine Learning: Dự báo & Phân cụm" \}\}': 'Machine Learning: Forecasting & Clustering',
    r'\{\{ "Tự động báo cáo qua Telegram" \}\}': 'Automated Reporting via Telegram',
    r'\{\{ "Đồng bộ Google Sheets Real-time" \}\}': 'Real-time Google Sheets Synchronization',
    r'\{\{ "Xuất báo cáo chuyên nghiệp \\(PDF/Word/Excel\\)" \}\}': 'Export Professional Reports (PDF/Word/Excel)',
    r'\{\{ "Bảo mật dữ liệu doanh nghiệp đa lớp" \}\}': 'Multi-layer Enterprise Data Security',
    r'\{\{ "Hỗ trợ VIP 1:1 & Đào tạo tận nơi" \}\}': 'VIP 1:1 Support & On-site Training',
    r'\{\{ "Nâng cấp Doanh nghiệp" \}\}': 'Upgrade to Enterprise',
    r'\{\{ "Câu hỏi hay gặp" \}\}': 'Frequently Asked Questions',
    r'\{\{ "Làm thế nào để kết nối Telegram báo cáo tự động\?" \}\}': 'How to connect Telegram for automated reporting?',
    r'\{\{ "Bạn chỉ cần thiết lập lịch trình trong mục Automation của Dashboard và kết nối Bot Token. Mia sẽ tự động quét dữ liệu và gửi biểu đồ phân tích trực tiếp vào nhóm Telegram của bạn theo định kỳ hàng ngày hoặc hàng tuần." \}\}': 'You simply configure the schedule in the Automation section of the Dashboard and connect the Bot Token. Mia will automatically scan data and send analysis charts directly to your Telegram group on a daily or weekly basis.',
    r'\{\{ "Dữ liệu của tôi có được bảo mật và riêng tư không\?" \}\}': 'Is my data secure and private?',
    r'\{\{ "An toàn dữ liệu là ưu tiên số 1. Chúng tôi sử dụng mã hóa AES-256 và bảo mật đa lớp chuẩn doanh nghiệp. Mia cam kết không chia sẻ dữ liệu của bạn cho bên thứ ba và không dùng dữ liệu này để huấn luyện AI công khai." \}\}': 'Data safety is our #1 priority. We use AES-256 encryption and enterprise-grade multi-layer security. Mia commits not to share your data with third parties and not to use this data to train public AIs.',
    r'\{\{ "Tôi không biết về kỹ thuật hay SQL thì có dùng được không\?" \}\}': 'Can I use it if I don\'t know about technical stuff or SQL?',
    r'\{\{ "Hoàn toàn được! Mia AI Data Analytics được thiết kế để phục vụ những người không am hiểu kỹ thuật. Bạn chỉ cần hỏi bằng ngôn ngữ tự nhiên như đang nói chuyện với một trợ lý, Mia sẽ tự động xử lý mọi phép toán phức tạp thay bạn." \}\}': 'Absolutely! Mia AI Data Analytics is designed to serve non-technical users. You just need to ask in natural language as if talking to an assistant, Mia will automatically handle all complex calculations for you.',
    r'\{\{ "Hệ thống có hỗ trợ các bộ dữ liệu lớn \\(Big Data\\) không\?" \}\}': 'Does the system support large datasets (Big Data)?',
    r'\{\{ "Có, Mia hỗ trợ xử lý các file Excel và CSV lên đến hàng triệu dòng. Đối với nhu cầu lưu trữ và phân tích lớn hơn, chúng tôi cung cấp giải pháp kết nối trực tiếp vào kho dữ liệu \\(Data Warehouse\\) của doanh nghiệp bạn." \}\}': 'Yes, Mia supports processing Excel and CSV files up to millions of rows. For larger storage and analysis needs, we offer solutions to connect directly to your enterprise Data Warehouse.',
    r'\{\{ "Tôi có thể sử dụng Mia AI Data Analytics trên điện thoại di động không\?" \}\}': 'Can I use Mia AI Data Analytics on a mobile phone?',
    r'\{\{ "Chắc chắn rồi. Giao diện của Mia được tối ưu hóa hoàn hảo cho di động và máy tính bảng. Bạn có thể theo dõi biểu đồ, xem báo cáo và chat với AI để nắm bắt tình hình kinh doanh mọi lúc, mọi nơi." \}\}': 'Certainly. Mia\'s interface is perfectly optimized for mobile and tablets. You can monitor charts, view reports, and chat with AI to grasp the business situation anytime, anywhere.',
    r'\{\{ "Mia AI Data Analytics có hỗ trợ nhiều ngôn ngữ không\?" \}\}': 'Does Mia AI Data Analytics support multiple languages?',
    r'\{\{ "Hoàn toàn có! Mia AI Data Analytics là một hệ thống đa ngôn ngữ thực thụ. Toàn bộ giao diện có thể được dịch tự động sang hơn 100 ngôn ngữ khác nhau qua Google Widget. Đặc biệt, bộ não AI của Mia có khả năng nhận diện và phản hồi trực tiếp bằng chính ngôn ngữ bạn đang nhắn \\(Tiếng Anh, Tiếng Trung, Tiếng Thổ Nhĩ Kỳ\.\.\.\\) một cách tự nhiên và chính xác." \}\}': 'Absolutely! Mia AI Data Analytics is a true multilingual system. You can switch the whole interface to English seamlessly without any auto-translation widget. Moreover, Mia\'s AI brain can recognize and respond directly in the exact language you chat in (English, Chinese, Turkish...) naturally and accurately.',
    r'\{\{ "Giải pháp phân tích dữ liệu AI hàng đầu cho doanh nghiệp Việt." \}\}': 'Leading AI data analytics solution for businesses.',
    r'\{\{ "Sản phẩm" \}\}': 'Products',
    r'\{\{ "Tính năng chính" \}\}': 'Core Features',
    r'\{\{ "Lộ trình phát triển" \}\}': 'Roadmap',
    r'\{\{ "Hỗ trợ" \}\}': 'Support',
    r'\{\{ "Tài liệu hướng dẫn" \}\}': 'Documentation',
    r'\{\{ "Chính sách bảo mật" \}\}': 'Privacy Policy',
    r'\{\{ "Điều khoản dịch vụ" \}\}': 'Terms of Service',
    r'\{\{ "Liên hệ" \}\}': 'Contact',
    r'\{\{ "Hotline: 1900-MIA-AI" \}\}': 'Hotline: 1900-MIA-AI',
    r'\{\{ "Tất cả quyền được bảo lưu." \}\}': 'All rights reserved.',
    r'\{\{ "Dashboard" \}\}': 'Dashboard'
}

for vi, en in translations.items():
    content = re.sub(vi, en, content)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Translation applied successfully.")
