# Generated by Django 5.2.12 on 2026-04-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_telegramsettings_automationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='schedule_type',
            field=models.CharField(default='daily', max_length=20),
        ),
    ]
