# Generated by Django 5.2.12 on 2026-04-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_fileuploadlog_useractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopeeCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.BigIntegerField()),
                ('access_token_enc', models.TextField()),
                ('refresh_token_enc', models.TextField()),
                ('expire_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopee_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopeeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.BigIntegerField()),
                ('order_sn', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('actual_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estimated_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('seller_transaction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('seller_rebate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('shopee_rebate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('voucher_seller', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('voucher_shopee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buyer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'shop_id'], name='analytics_s_user_id_adcb18_idx'), models.Index(fields=['create_time'], name='analytics_s_create__003a5c_idx')],
            },
        ),
    ]
