# Generated by Django 5.2.12 on 2026-04-29 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_userdataset_datasetrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='agg_func',
            field=models.CharField(default='SUM', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.userdataset'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='label_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='value_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='chart_type',
            field=models.CharField(default='bar', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
