# Generated by Django 5.2.12 on 2026-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_dashboardwidget_agg_func_dashboardwidget_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdashboard',
            name='layout_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
