# Generated by Django 5.2.12 on 2026-05-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_customdashboard_layout_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='style_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
