# Generated by Django 5.2.12 on 2026-05-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_dashboardwidget_style_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('SAVE_REPORT', 'Lưu báo cáo'), ('DOWNLOAD_CHART', 'Tải biểu đồ'), ('SHARE_LINK', 'Chia sẻ liên kết'), ('COPY_SQL', 'Sao chép SQL'), ('JOIN_TABLES', 'Join bảng')], max_length=50),
        ),
        migrations.CreateModel(
            name='CalculatedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('formula', models.TextField()),
                ('type', models.CharField(choices=[('MEASURE', 'Measure'), ('COLUMN', 'Column')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='analytics.userdataset')),
            ],
        ),
    ]
