# Generated by Django 5.2.12 on 2026-05-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_useractionlog_action_type_calculatedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
