# Generated by Django 5.2.12 on 2026-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_userdataset_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='is_auto_refresh',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdataset',
            name='refresh_interval',
            field=models.CharField(choices=[('hourly', 'Hàng giờ'), ('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='userdataset',
            name='source_sql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
