# Generated by Django 5.2.12 on 2026-05-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_userdataset_is_auto_refresh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('kiotviet', 'KiotViet'), ('facebook_ads', 'Facebook Ads'), ('google_ads', 'Google Ads/AdSense')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key_enc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgres', 'PostgreSQL'), ('sqlserver', 'SQL Server')], max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password_enc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_creds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
