# Generated by Django 5.2.12 on 2026-05-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_eltworkflow_eltpipelinelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='eltworkflow',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
