# Generated by Django 5.2.14 on 2026-05-12 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_anomalyalertconfig_sharedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='connector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.databasecredential'),
        ),
    ]
