# Generated by Django 5.2.14 on 2026-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0020_userdataset_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataset',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
