# Generated by Django 5.2.14 on 2026-05-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0021_userdataset_last_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
