# Generated by Django 5.2.12 on 2026-06-08 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0023_automationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SCMOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_source', models.CharField(choices=[('shopee', 'Shopee'), ('tiktok', 'TikTok Shop'), ('lazada', 'Lazada'), ('tiki', 'Tiki'), ('other', 'Khác')], default='shopee', max_length=50)),
                ('shop_id', models.BigIntegerField(blank=True, null=True)),
                ('order_sn', models.CharField(max_length=50, unique=True)),
                ('order_status', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField()),
                ('pay_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('actual_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('estimated_shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('seller_transaction_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('seller_rebate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('platform_rebate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('voucher_seller', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('voucher_platform', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buyer_username', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(default=0, help_text='Thời gian giao hàng trung bình (ngày)')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Điểm đánh giá chất lượng (1-5)', max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0, help_text='Tồn kho an toàn tối thiểu')),
                ('reorder_point', models.IntegerField(default=0, help_text='Điểm đặt hàng lại')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopeeOrder',
        ),
        migrations.AddIndex(
            model_name='scmorder',
            index=models.Index(fields=['user', 'platform_source', 'shop_id'], name='analytics_s_user_id_21d596_idx'),
        ),
        migrations.AddIndex(
            model_name='scmorder',
            index=models.Index(fields=['create_time'], name='analytics_s_create__890520_idx'),
        ),
    ]
