# Generated by Django 5.2.12 on 2026-03-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Miễn phí'), ('PLUS', 'Chuyên nghiệp'), ('PREMIUM', 'Doanh nghiệp')], default='FREE', max_length=20),
        ),
    ]
