# Generated by Django 5.2.12 on 2026-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Cơ bản'), ('PLUS', 'Nâng cao'), ('PREMIUM', 'Chuyên nghiệp')], default='FREE', max_length=10),
        ),
    ]
