# Generated by Django 5.2.12 on 2026-04-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
