# Generated by Django 5.2.12 on 2026-04-08 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_subscription_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('FREE_PLUS_7_DAYS', 'Miễn phí Plus 7 ngày'), ('DISCOUNT_PERCENT', 'Giảm % cho tất cả gói'), ('FIXED_DISCOUNT', 'Giảm số tiền cố định')], max_length=50)),
                ('discount_val', models.IntegerField(blank=True, help_text='Tỷ lệ % hoặc số tiền cố định', null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.voucher')),
            ],
            options={
                'unique_together': {('voucher', 'user')},
            },
        ),
    ]
