# Generated by Django 5.2.12 on 2026-05-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Miễn phí'), ('PLUS', 'Chuyên nghiệp'), ('PREMIUM', 'Chuyên nghiệp')], default='FREE', max_length=10),
        ),
    ]
