# Generated by Django 5.2.14 on 2026-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Cơ bản'), ('FREE', 'Cơ bản'), ('ADVANCED', 'Nâng cao'), ('PLUS', 'Nâng cao'), ('ENTERPRISE', 'Doanh nghiệp'), ('PREMIUM', 'Doanh nghiệp')], default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('FREE_ADVANCED_7_DAYS', 'Miễn phí Nâng cao 7 ngày'), ('DISCOUNT_PERCENT', 'Giảm % cho tất cả gói'), ('FIXED_DISCOUNT', 'Giảm số tiền cố định')], max_length=50),
        ),
    ]
