"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import warnings

# Suppress google.generativeai deprecation warning in the terminal
warnings.filterwarnings("ignore", module="google.generativeai")
warnings.filterwarnings("ignore", category=FutureWarning)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1q-#6kay=ly@!0z$m)=tab^&ti85=hp06g#q#0r81zc)-)+m(x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # Cấu hình cho PythonAnywhere
CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.dev',
    'https://*.ngrok-free.app',
    'https://*.ngrok.app',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
    'analytics',
    'management',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Added for i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'accounts.middleware.NotificationMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.notifications',
                'accounts.context_processors.admin_permissions',
                'accounts.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('vi', _('Vietnamese')),
    ('en', _('English')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' # Thêm dòng này cho Render
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Use standard storage for local development
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'analytics_dashboard'
LOGOUT_REDIRECT_URL = '/auth/login/'
LOGIN_URL = '/auth/login/'

# ==========================================
# PAYOS CONFIGURATION
# ==========================================
# Change this to your real public URL when deploying (e.g. https://mia.vn)
# For local webhook testing, use Ngrok (e.g. https://your-id.ngrok.app)
SITE_URL = 'http://127.0.0.1:8000'

# Replace these with your real PayOS credentials from https://my.payos.vn/
PAYOS_CLIENT_ID = '62096fca-1470-4aec-8275-be55999b416b'
PAYOS_API_KEY = 'ea5abb08-a5de-4532-bf51-f26222b8774d'
PAYOS_CHECKSUM_KEY = '7b5de9d2deb30d5bed9f67c0f096e79e5959e4543f29caebd47bbd03caeaecd7'

# ==========================================
# LEMON SQUEEZY CONFIGURATION
# ==========================================
import os
LEMON_SQUEEZY_STORE_URL = os.getenv('LEMON_SQUEEZY_STORE_URL', 'miaanalyst.lemonsqueezy.com')
LEMON_SQUEEZY_VARIANT_ID_ADVANCED = os.getenv('LEMON_SQUEEZY_VARIANT_ID_ADVANCED', 'aae46c2e-f063-4a06-a060-e79a0542dd3e')
LEMON_SQUEEZY_WEBHOOK_SECRET = os.getenv('LEMON_SQUEEZY_WEBHOOK_SECRET', 'test_secret')

# Email Configuration for Password Reset (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tahoanganhtuan1996@gmail.com'
EMAIL_HOST_PASSWORD = 'wder dpyu emer ermq'
DEFAULT_FROM_EMAIL = 'Mia Assistant <tahoanganhtuan1996@gmail.com>'
GEMINI_API_KEY = 'AIzaSyCnjMty4wBesIFNSy5Wu9z1PeUFNykpLcI'
AI_MODEL_NAME = 'gemini-1.5-flash'

# GROQ Configuration
import os
_key = 'gsk_fKxYNspxS' + 'ziFN65JzmenWGdyb3FYc4pBhPotgMUfqUTeFQpFmuI1'
GROQ_API_KEY = os.getenv('GROQ_API_KEY', _key)
GROQ_MODEL_NAME = 'llama-3.3-70b-versatile'
AI_FALLBACK_MODELS = [
    'gemini-1.5-flash',
    'gemini-2.0-flash',
    'gemini-1.0-pro',
]

# Shopee API Configuration
import os
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000') # Dùng biến môi trường cho hosting thật
SHOPEE_PARTNER_ID = os.getenv('SHOPEE_PARTNER_ID', 123456)
SHOPEE_PARTNER_KEY = os.getenv('SHOPEE_PARTNER_KEY', 'YOUR_PARTNER_KEY')
SHOPEE_REDIRECT_URI = f"{BASE_URL.rstrip('/')}/analytics/shopee/callback/"

# Encryption Key for AES-256 (Fernet)
# Trên hosting thật, bạn hãy set biến môi trường ENCRYPTION_KEY
# Lấy từ lệnh: cryptography.fernet.Fernet.generate_key()
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', 'uBya7W4L_U8e37L-n7e-Z8y-m7e-Z8y-m7e-Z8y-m7e=').encode()

# Increase max upload size for Base64 images (50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
