# Generated by Django 5.2.12 on 2026-04-21 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('solutions', 'Solutions'), ('knowledge', 'Knowledge'), ('technology', 'Technology'), ('case_study', 'Case Study')], default='knowledge', max_length=50)),
                ('author_pseudonym', models.CharField(blank=True, help_text='Bút danh (sẽ lưu lại cho lần sau)', max_length=100)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('summary', models.TextField(help_text='Phần tóm tắt hiển thị dưới tiêu đề như trong hình (hỗ trợ HTML).')),
                ('content', models.TextField(help_text='Nội dung chính (nhúng TinyMCE HTML).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Hẹn giờ đăng bài theo ngày/giờ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
