# Generated by Django 5.2.12 on 2026-04-21 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_alter_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='Thời gian tính bằng giây')),
                ('scroll_depth', models.FloatField(help_text='Tỷ lệ cuộn từ 0 đến 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='blog.post')),
            ],
            options={
                'verbose_name': 'Phiên đọc',
                'verbose_name_plural': 'Các phiên đọc',
            },
        ),
    ]
