# Generated by Django 5.2.12 on 2026-05-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_readingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
